# Generated by Django 3.0.4 on 2020-03-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='user',
        ),
    ]
